name: Deploy Pexels Search

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  VITE_APP_TITLE: "Buscador Pexels"
  VITE_DEFAULT_QUERY: "nature"
  VITE_MAX_PHOTOS: 20
  VITE_API_CACHE_ENABLED: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build app
        run: npm run build
        env:
          VITE_PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          VITE_APP_MODE: production
      
      - name: Create API cache
        run: |
          mkdir -p dist/api
          SEARCH_TERMS=("nature" "beach" "mountains" "city" "people" "animals" "food" "technology" "sports" "business")
          
          for term in "${SEARCH_TERMS[@]}"; do
            echo "📦 Cacheando: $term"
            curl -s -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" \
              "https://api.pexels.com/v1/search?query=$term&per_page=${{ env.VITE_MAX_PHOTOS }}" > "dist/api/$term.json" || echo "⚠️ Error cacheando $term"
            sleep 1
          done
          
          # Cachear la búsqueda por defecto
          cp "dist/api/${{ env.VITE_DEFAULT_QUERY }}.json" dist/api/default.json
      
      - name: Verify build
        run: |
          [ -d dist ] || exit 1
          [ -f dist/index.html ] || exit 1
          [ -d dist/api ] || exit 1
          echo "✅ Build verificado"
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
