name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # Add this step to fetch and cache Pexels data
      - name: Pre-fetch Pexels API data
        run: |
          mkdir -p public/api
          # Fetch default images (nature)
          curl -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" \
            "https://api.pexels.com/v1/search?query=nature&per_page=15" > public/api/nature.json
          # Add more common searches to pre-cache
          curl -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" \
            "https://api.pexels.com/v1/search?query=beach&per_page=15" > public/api/beach.json
          curl -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" \
            "https://api.pexels.com/v1/search?query=mountains&per_page=15" > public/api/mountains.json
          curl -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" \
            "https://api.pexels.com/v1/search?query=city&per_page=15" > public/api/city.json
          curl -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" \
            "https://api.pexels.com/v1/search?query=forest&per_page=15" > public/api/forest.json
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Vite builds to the dist folder by default

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
